2025-03-14 20:35:27,403 INFO    MainThread:7659 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/hiran/Desktop/DL/wandb/run-20250314_203527-8hx6aqpp/logs/debug.log
2025-03-14 20:35:27,403 INFO    MainThread:7659 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/hiran/Desktop/DL/wandb/run-20250314_203527-8hx6aqpp/logs/debug-internal.log
2025-03-14 20:35:27,403 INFO    MainThread:7659 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f82868b81f0>
2025-03-14 20:35:27,404 INFO    MainThread:7659 [wandb_init.py:init():761] calling init triggers
2025-03-14 20:35:27,404 INFO    MainThread:7659 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-14 20:35:27,404 INFO    MainThread:7659 [wandb_init.py:init():784] starting backend
2025-03-14 20:35:27,404 INFO    MainThread:7659 [wandb_init.py:init():788] sending inform_init request
2025-03-14 20:35:27,405 INFO    MainThread:7659 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-14 20:35:27,405 INFO    MainThread:7659 [wandb_init.py:init():798] backend started and connected
2025-03-14 20:35:27,406 INFO    MainThread:7659 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-14 20:35:27,406 INFO    MainThread:7659 [wandb_init.py:init():891] updated telemetry
2025-03-14 20:35:27,406 ERROR   MainThread:7659 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "/home/hiran/Desktop/DL/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
  File "/home/hiran/Desktop/DL/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 898, in init
    backend.interface.publish_header()
  File "/home/hiran/Desktop/DL/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 97, in publish_header
    self._publish_header(header)
  File "/home/hiran/Desktop/DL/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 275, in _publish_header
    self._publish(rec)
  File "/home/hiran/Desktop/DL/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/hiran/Desktop/DL/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/hiran/Desktop/DL/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/hiran/Desktop/DL/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/hiran/Desktop/DL/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
