2025-03-14 19:52:32,851 INFO    MainThread:7659 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/hiran/Desktop/DL/wandb/run-20250314_195232-l1xf5kvp/logs/debug.log
2025-03-14 19:52:32,851 INFO    MainThread:7659 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/hiran/Desktop/DL/wandb/run-20250314_195232-l1xf5kvp/logs/debug-internal.log
2025-03-14 19:52:32,851 INFO    MainThread:7659 [wandb_init.py:init():761] calling init triggers
2025-03-14 19:52:32,851 INFO    MainThread:7659 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-14 19:52:32,851 INFO    MainThread:7659 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-14 19:52:41,667 INFO    MainThread:7659 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-14 19:52:41,667 INFO    MainThread:7659 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-14 19:53:31,800 INFO    MainThread:7659 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-14 19:53:32,103 INFO    MainThread:7659 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/hiran/Desktop/DL/wandb/run-20250314_195332-dwnjes2o/logs/debug.log
2025-03-14 19:53:32,103 INFO    MainThread:7659 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/hiran/Desktop/DL/wandb/run-20250314_195332-dwnjes2o/logs/debug-internal.log
2025-03-14 19:53:32,103 INFO    MainThread:7659 [wandb_init.py:init():761] calling init triggers
2025-03-14 19:53:32,103 INFO    MainThread:7659 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-14 19:53:32,103 INFO    MainThread:7659 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-14 19:53:32,255 INFO    MainThread:7659 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-14 19:53:32,255 INFO    MainThread:7659 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-14 19:53:51,940 INFO    MainThread:7659 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-14 19:53:52,312 INFO    MainThread:7659 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-14 19:53:52,313 INFO    MainThread:7659 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-14 19:56:44,002 INFO    MainThread:7659 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-14 19:56:44,547 INFO    MainThread:7659 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-14 19:56:44,548 INFO    MainThread:7659 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-14 20:00:08,791 INFO    MainThread:7659 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-14 20:00:18,283 INFO    MainThread:7659 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-14 20:00:18,283 INFO    MainThread:7659 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-14 20:00:48,781 INFO    MainThread:7659 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-14 20:00:49,076 INFO    MainThread:7659 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/hiran/Desktop/DL/wandb/run-20250314_200049-yrlihlrn/logs/debug.log
2025-03-14 20:00:49,077 INFO    MainThread:7659 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/hiran/Desktop/DL/wandb/run-20250314_200049-yrlihlrn/logs/debug-internal.log
2025-03-14 20:00:49,077 INFO    MainThread:7659 [wandb_init.py:init():761] calling init triggers
2025-03-14 20:00:49,077 INFO    MainThread:7659 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-14 20:00:49,077 INFO    MainThread:7659 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-14 20:00:57,994 INFO    MainThread:7659 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-14 20:00:57,995 INFO    MainThread:7659 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-14 20:02:31,671 INFO    MainThread:7659 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-14 20:02:31,959 INFO    MainThread:7659 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/hiran/Desktop/DL/wandb/run-20250314_200231-6o96k914/logs/debug.log
2025-03-14 20:02:31,959 INFO    MainThread:7659 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/hiran/Desktop/DL/wandb/run-20250314_200231-6o96k914/logs/debug-internal.log
2025-03-14 20:02:31,959 INFO    MainThread:7659 [wandb_init.py:init():761] calling init triggers
2025-03-14 20:02:31,959 INFO    MainThread:7659 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-14 20:02:31,959 INFO    MainThread:7659 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-14 20:02:41,061 INFO    MainThread:7659 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-14 20:02:41,061 INFO    MainThread:7659 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-14 20:03:22,385 INFO    MainThread:7659 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-14 20:03:22,389 INFO    MainThread:7659 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-14 20:03:22,390 INFO    MainThread:7659 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-14 20:03:24,885 INFO    MainThread:7659 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-14 20:03:24,889 INFO    MainThread:7659 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-14 20:03:24,890 INFO    MainThread:7659 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-14 20:03:25,907 INFO    MainThread:7659 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-14 20:03:25,911 INFO    MainThread:7659 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-14 20:03:25,911 INFO    MainThread:7659 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-14 20:03:26,041 INFO    MainThread:7659 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-14 20:03:26,045 INFO    MainThread:7659 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-14 20:03:26,045 INFO    MainThread:7659 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-14 20:04:08,812 INFO    MainThread:7659 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-14 20:04:09,091 INFO    MainThread:7659 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/hiran/Desktop/DL/wandb/run-20250314_200409-dg19a4xj/logs/debug.log
2025-03-14 20:04:09,091 INFO    MainThread:7659 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/hiran/Desktop/DL/wandb/run-20250314_200409-dg19a4xj/logs/debug-internal.log
2025-03-14 20:04:09,091 INFO    MainThread:7659 [wandb_init.py:init():761] calling init triggers
2025-03-14 20:04:09,092 INFO    MainThread:7659 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-14 20:04:09,092 INFO    MainThread:7659 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-14 20:04:18,063 INFO    MainThread:7659 [wandb_run.py:_finish():2112] finishing run mm21b030-indian-institute-of-technology-madras/DL/lgrd970h
2025-03-14 20:04:18,064 ERROR   MainThread:7659 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-03-14 20:04:18,064 INFO    MainThread:7659 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-14 20:04:18,064 INFO    MainThread:7659 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-03-14 20:04:18,064 INFO    MainThread:7659 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 0
2025-03-14 20:04:18,064 INFO    MainThread:7659 [wandb_run.py:_restore():2322] restore
2025-03-14 20:04:18,064 INFO    MainThread:7659 [wandb_run.py:_restore():2328] restore done
2025-03-14 20:04:19,793 INFO    MainThread:7659 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-03-14 20:04:19,793 INFO    MainThread:7659 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-03-14 20:04:19,795 INFO    MainThread:7659 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-03-14 20:34:40,478 WARNING MsgRouterThr:7659 [router.py:message_loop():63] message_loop has been closed
Traceback (most recent call last):
  File "/home/hiran/Desktop/DL/.venv/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
  File "/home/hiran/Desktop/DL/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/home/hiran/Desktop/DL/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hiran/Desktop/DL/.venv/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
  File "/home/hiran/Desktop/DL/.venv/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-14 20:34:40,512 INFO    MsgRouterThr:7659 [mailbox.py:close():129] Closing mailbox, abandoning 2 handles.
2025-03-14 20:35:27,403 INFO    MainThread:7659 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/hiran/Desktop/DL/wandb/run-20250314_203527-8hx6aqpp/logs/debug.log
2025-03-14 20:35:27,403 INFO    MainThread:7659 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/hiran/Desktop/DL/wandb/run-20250314_203527-8hx6aqpp/logs/debug-internal.log
2025-03-14 20:35:27,403 INFO    MainThread:7659 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f82868b81f0>
2025-03-14 20:35:27,404 INFO    MainThread:7659 [wandb_init.py:init():761] calling init triggers
2025-03-14 20:35:27,404 INFO    MainThread:7659 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-14 20:35:27,404 INFO    MainThread:7659 [wandb_init.py:init():784] starting backend
2025-03-14 20:35:27,404 INFO    MainThread:7659 [wandb_init.py:init():788] sending inform_init request
2025-03-14 20:35:27,405 INFO    MainThread:7659 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-14 20:35:27,405 INFO    MainThread:7659 [wandb_init.py:init():798] backend started and connected
2025-03-14 20:35:27,406 INFO    MainThread:7659 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-14 20:35:27,406 INFO    MainThread:7659 [wandb_init.py:init():891] updated telemetry
2025-03-14 20:35:27,406 ERROR   MainThread:7659 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "/home/hiran/Desktop/DL/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
  File "/home/hiran/Desktop/DL/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 898, in init
    backend.interface.publish_header()
  File "/home/hiran/Desktop/DL/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 97, in publish_header
    self._publish_header(header)
  File "/home/hiran/Desktop/DL/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 275, in _publish_header
    self._publish(rec)
  File "/home/hiran/Desktop/DL/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/hiran/Desktop/DL/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/hiran/Desktop/DL/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/hiran/Desktop/DL/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/hiran/Desktop/DL/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
